from google import genai
from google.genai import types
from PIL import Image
import os
from supabase import create_client, Client
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def generate_prompt(activity: str) -> str:
    prompt = (
        f"""
        Create a high-quality, aesthetic, cute horizontal banner illustration for a student activity planning web app.

        Main focus:
        - Show a small group of diverse college-age students actively engaged in: {activity}.
        - The scene should clearly represent the activity while staying friendly, positive, and inviting.
        - Characters should look modern, expressive, and relatable.

        Composition:
        - CRITICAL: Wide horizontal banner in 16:9 aspect ratio (1920x1080 or similar).
        - Fill the ENTIRE width of the image edge-to-edge with the scene - NO white borders or empty margins.
        - The scene should extend to all four edges of the canvas.
        - Keep main characters slightly off-center with intentional compositional space to allow overlaid UI text.
        - Background should imply the correct environment (outdoor field, living room, study area, etc.) but remain simple, uncluttered, and secondary to the characters.
        - Medium-distance perspective so faces and body language are readable.
        - Use a full, immersive background that fills the entire frame.

        Art Direction:
        - Clean, modern illustration suitable for a web interface.
        - Soft, cohesive color palette with smooth lighting.
        - Avoid extreme stylization — keep it balanced (not overly cartoonish, not hyper-realistic).
        - No text, no logos, no watermarks, no UI elements.
        - NO white space, NO borders, NO padding - the illustration must bleed to the edges.

        Details:
        - Lighting should match the activity (daylight for outdoors, soft warm lighting for indoors).
        - Include subtle props or context elements that reinforce the activity without crowding the frame.
        - Characters should include gender and ethnic diversity and wear activity-appropriate casual clothing.
        - Ensure the background environment extends fully to all edges of the image.

        Output:
        - Generate one edge-to-edge horizontal banner illustration in 16:9 aspect ratio optimized for use as a card header image.
        """
    )

    return prompt

def main():
    activities_list= [
        "Going for a walk",
        "Hiking a local trail",
        "Sunset viewing",
        "Stargazing",
        "Picnic at the park",
        "Playing soccer",
        "Playing basketball",
        "Playing volleyball",
        "Playing frisbee",
        "Playing ultimate frisbee",
        "Playing catch",
        "Going for a jog",
        "Biking together",
        "Rollerblading",
        "Skateboarding",
        "Flying a kite",
        "Visiting a botanical garden",
        "Outdoor yoga",
        "Outdoor meditation",
        "Going to a lake",
        "Swimming at the beach",
        "Exploring a nature preserve",
        "Paddle boating",
        "Kayaking",
        "Canoeing",
        "Fishing",
        "Visiting a farmer’s market",
        "Taking photos outside",
        "Walking dogs",
        "Exploring a new neighborhood",
        "Outdoor workout session",
        "Doing a scavenger hunt",
        "Playing mini-golf",
        "Going to a driving range",
        "Going to a batting cage",
        "Going to a zoo",
        "Going to an aquarium",
        "Going to an outdoor concert",
        "Going to a street festival",
        "Going to a food truck festival",
        "Doing a BBQ",
        "Gardening together",
        "Playing badminton",
        "Playing pickleball",
        "Playing tennis",
        "Going on a campus tour",
        "Geocaching",
        "Riding scooters",
        "Drone flying",
        "Outdoor board games",
        "Outdoor movie screening",
        "Visiting a scenic overlook",
        "Jogging with friends",
        "Doing a group stretch",
        "Visiting a skate park",
        "Visiting a dog park",
        "Exploring campus landmarks",
        "Campus photography walk",
        "Doing chalk art outside",
        "Playing water balloon games",
        "Snowball fight",
        "Ice skating outdoors",
        "Building a snowman",
        "Nature sketching",
        "Feeding ducks at a pond",
        "Observatory visit",
        "Bonfire hangout",
        "Watching fireworks",
        "Beach volleyball",
        "Canoe racing",
        "Rock climbing outdoors",
        "Playing tag",
        "Relay races",
        "Frisbee golf",
        "Visiting a historical site",
        "Sandcastle building",
        "Visiting an arboretum",
        "Watching a sunrise",
        "Visiting a flower field",
        "Outdoor puzzle solving",

        # Indoor hangouts
        "Movie night",
        "Game night",
        "Board games",
        "Card games",
        "Watching TV together",
        "Binge-watching a show",
        "Making popcorn",
        "Karaoke night",
        "Cooking a meal",
        "Baking cookies",
        "Trying new recipes",
        "Having a potluck",
        "Eating takeout together",
        "Doing a puzzle",
        "Playing video games",
        "Playing console games",
        "Playing PC games",
        "VR gaming",
        "Watching anime",
        "Playing music together",
        "Doing a craft session",
        "Candle making",
        "Soap making",
        "Painting",
        "Drawing session",
        "Scrapbooking",
        "Coloring books",
        "Origami",
        "Building Legos",
        "Building a model kit",
        "Reading together",
        "Listening to music",
        "Dance party",
        "Practicing an instrument",
        "Singing together",
        "Writing stories",
        "Studying together",
        "Doing homework together",
        "Working on a project",
        "Study group session",
        "Brainstorming ideas",
        "Sharing life updates",
        "Indoor picnic",
        "Home workout",
        "Meditation session",
        "Watching YouTube videos",
        "Chatting about goals",
        "Movie marathon",
        "Playing air hockey",
        "Playing billiards",
        "Playing ping-pong",
        "Playing foosball",
        "Playing darts",
        "Solving riddles",
        "Escape room puzzles at home",
        "Trying new snacks",
        "Taste-testing foods",
        "Practicing photography indoors",
        "Decorating a room",
        "Holiday decorating",
        "Preparing for a surprise party",
        "Watching documentaries",
        "Listening to a podcast",
        "Tea time",
        "Coffee tasting",
        "Trying new drinks",
        "Mocktail making",
        "Learning TikTok dances",
        "Group journaling",
        "Planning a trip",
        "Planning a party",
        "Trying DIY home projects",
        "Houseplant care hangout",
        "Aquarium maintenance",
        "Watching sports together",
        "Fantasy sports planning",
        "Indoor mini-games",
        "Domino toppling",
        "Playing charades",
        "Playing Pictionary",

        # Food & restaurant activities
        "Going out for brunch",
        "Going out for dinner",
        "Trying a new café",
        "Visiting a dessert shop",
        "Going to an ice cream parlor",
        "Bubble tea hangout",
        "Smoothie shop visit",
        "Milkshake run",
        "Donut shop visit",
        "Trying street food",
        "Going to a steakhouse",
        "Sushi night",
        "Ramen night",
        "Hot pot outing",
        "Korean BBQ outing",
        "Taco Tuesday",
        "Pizza night",
        "Dim sum brunch",
        "Pho night",
        "Sandwich shop visit",
        "Food court hangout",
        "Trying a new bar",
        "Coffee shop study hangout",
        "Bakery visit",
        "Chocolate tasting",
        "Pie tasting",
        "Group cooking class",
        "Going to a buffet",
        "Cafe hopping",
        "Going to a farmer's market",
        "Trying international cuisine",
        "Sharing appetizers",
        "Dessert tasting flight",
        "Trying pastries",
        "Juice bar hangout",
        "Visiting a rooftop restaurant",
        "Visiting a food truck",
        "Going to a themed café",
        "Brunch to-go and eating outside",
        "Trying new breakfast places",
        "Brunch photoshoot",
        "Late-night diner visit",
        "Fast food hangout",
        "Pancake night",
        "Waffle night",
        "Group grilling",
        "Fondue night",
        "DIY pizza night",
        "Donut run",
        "Café study date",
        "Coffee and conversation",
        "Dessert and walk combo",
        "Trying seasonal drinks",
        "Sampling pastries",
        "Ordering new menus",
        "Food taste challenge",
        "Tea sampling",
        "Visiting a juice truck",
        "Visiting a campus café",
        "Trying gourmet burgers",
        "Sharing a giant dessert",
        "Visiting a ramen shop",
        "Trying a new sushi roll",
        "Cafeteria hangout",
        "Breakfast sandwiches outing",
        "Food photography hangout",
        "Trying new sauces",
        "Trying plant-based foods",
        "Buying snacks for game night",
        "Trying limited-edition foods",

        # Low-key social activities
        "Talking on the couch",
        "Deep conversation session",
        "Sharing personal stories",
        "Planning goals together",
        "Listening to calm music",
        "Mindfulness hangout",
        "Sharing weekly highs and lows",
        "Laughing together",
        "Giving each other advice",
        "Catching up after a long day",
        "Sharing memes",
        "TikTok scrolling session",
        "Personality quizzes",
        "Sharing old photos",
        "Browsing Pinterest",
        "Creating vision boards",
        "Rating movies",
        "Reviewing music",
        "Doing each other’s hair",
        "Makeup practice",
        "Skin care routine hangout",
        "Outfit try-on session",
        "Closet clean-out",
        "Gift wrapping",
        "Planning birthdays",
        "Casual storytelling",
        "Sharing secrets",
        "Cultural exchange hangout",
        "Making bucket lists",
        "Gratitude exercises",
        "Couch gaming",
        "Cozy card game session",
        "Watching funny videos",
        "Sharing playlists",
        "Collaborative journaling",
        "Group meditation",
        "Painting nails",
        "Face masks hangout",
        "Trying new hairstyles",
        "Apartment decorating",
        "Sharing random facts",
        "Cooking and chatting",
        "Doodling together",
        "Watching pet videos",
        "Sharing life updates",
        "Planning future trips",
        "Window shopping",
        "Thrift store browsing",
        "Plant shopping",
        "Bookstore hangout",
        "Library study hangout",
        "College campus hangout",
        "Watching campus events",
        "Sitting on a rooftop",
        "Talking on a balcony",
        "Dorm lounge hangout",
        "Quiet relaxation hangout",
        "Vision board crafting",
        "Comparing class schedules",
        "Shared to-do list session",
        "Organizing a workspace",
        "Trying perfumes or colognes",
        "Fashion brainstorming",
        "Watching sunsets from campus",
        "Reflecting on goals",
        "Planning the week",
        "Sharing music recommendations",
        "Gentle stretching",
        "Day planning session",
        "Organizing digital files",
        "Unpacking shopping bags",
        "Group budgeting",
        "Rating new snacks",
        "Planning weekend events",
        "Doing nothing together",
        "Planning study strategies",
        "Making a dream board",
        "Sharing academic advice",
        "Organizing calendars",

        # High-energy / fun activities
        "Laser tag",
        "Bowling",
        "Indoor go-kart racing",
        "Escape room",
        "Trampoline park",
        "Arcade visit",
        "Mini bowling",
        "Nerf gun battle",
        "Water park visit",
        "Paintball",
        "Batting cage",
        "Indoor rock climbing",
        "Indoor ziplining",
        "Bounce house hangout",
        "Ropes course",
        "Ice skating indoors",
        "Roller rink visit",
        "Dance-off",
        "Improv comedy session",
        "Talent show",
        "Lip sync battle",
        "Silent disco",
        "Trivia night",
        "Bingo night",
        "Murder mystery game",
        "Speed friending",
        "Magic show outing",
        "Concert hangout",
        "Listening party",
        "DJ night",
        "Costume party",
        "Glow stick party",
        "Flash mob rehearsal",
        "TikTok dance challenge",
        "DIY bowling",
        "Indoor obstacle course",
        "Fitness class together",
        "Zumba hangout",
        "Martial arts class",
        "Yoga class",
        "Spin class",
        "Aerobics session",
        "Light workout hangout",
        "Obstacle race",
        "Silent reading party",
        "Meditation circle",
        "Strategy board games",
        "Puzzle speed challenge",
        "Card tournament",
        "Team-based trivia",
        "Quick sketch battles",
        "Speed origami",
        "Paper airplane contest",
        "Talent sharing session",
        "Lip reading challenge",
        "Whisper challenge",
        "Guess the song challenge",
        "Marshmallow tossing game",
        "Charade relay",
        "Guess-the-movie challenge",
        "Word association game",
        "Blindfold taste test",
        "Truth-or-dare (PG)",
        "TikTok karaoke",
        "Fast drawing challenge",
        "One-minute craft challenge",
        "Rapid-fire storytelling",
        "Joke telling challenge",
        "Mini scavenger hunt indoors",
        "5-minute build challenge",
        "Indoor relay races",
        "Mystery box guessing",
        "Duck duck goose",
        "Freeze dance",
        "Tabletop shuffleboard",
        "Indoor corn hole",
        "Indoor ring toss",
        "Foam sword dueling",
        "Water bottle flipping",
        "Jenga challenge",
        "Uno tournament",
        "Mafia game",
        "Werewolf game",
        "Spyfall game",
        "Group TikTok filming",

        # Creative / academic / project activities
        "Brainstorming a project",
        "Working on a startup idea",
        "Coding together",
        "Debugging together",
        "Whiteboard planning",
        "Creating a mind map",
        "Chemistry lab simulation",
        "Working on an engineering project",
        "Designing graphics together",
        "Editing videos",
        "Filming a short scene",
        "Recording a podcast",
        "Making a slideshow",
        "Creating digital art",
        "Practicing photography",
        "Learning a new skill together",
        "Language practice hangout",
        "Studying flashcards",
        "Planning essays",
        "Reviewing notes",
        "Group quiz session",
        "Reading research papers",
        "Designing posters",
        "Brainstorming inventions",
        "Planning class schedules",
        "Working on career prep",
        "LinkedIn review hangout",
        "Resume workshop",
        "Mock interview hangout",
        "Professional goal setting",
        "Creating presentations",
        "Building a small robot",
        "Soldering practice",
        "Experimenting with Arduino",
        "CAD modeling hangout",
        "Practicing public speaking",
        "Debate practice",
        "Practicing math problems",
        "Group study drills",
        "Reviewing practice exams",
        "Designing a study guide",
        "Planning a group project",
        "Reviewing class slides",
        "Productivity planning",
        "Time-management workshop",
        "Digital organization session",
        "Brainstorming club ideas",
        "Working on a passion project",
        "Mindfulness journaling",
        "Review session for finals",
        "Programming challenge hangout",
        "Coloring digital art",
        "Music production session",
        "Practicing beats",
        "Learning guitar chords",
        "Practicing piano together",
        "Songwriting session",
        "Trying AI tools together",
        "Photo editing hangout",
        "Graphic design challenge",
        "Whiteboard doodling",
        "Animation practice",
        "DIY engineering modeling",
        "Prototyping ideas",
        "Sketching inventions",
        "Drawing concept art",
        "Planning a YouTube video",
        "Filming study content",
        "Making motivational posters",
        "Experimenting with 3D printing",
        "Writing code challenges",
        "Creating study flashcards",
        "Reviewing past homework",
        "Solving logic puzzles",
        "Learning new formulas",
        "Studying physics together",
        "Practicing presentation skills",
        "Doing research together",
        "Creating a Canva design",
        "Editing resumes",
        "Planning a group workshop",
        "Productivity habit tracking",
        "Practicing storytelling",
        "Designing a logo",
        "Building a Minecraft world together",
        "Brainstorming app ideas",
        "Learning Blender basics",
        "Planning a hackathon project",
        "Group reading of a textbook",
        "Writing practice problems",
        "Math puzzle hangout",
        "Study sprint session",
        "Reviewing coding interviews",
        "Group Pomodoro session",
        "Tech demo sharing",
        "Brainstorming business strategies",
        "Whiteboard algorithm practice",
        "Pair programming",
        "Creating moodboards",
        "Trying new productivity apps",
        "Watching tutorial videos",
        "Brainstorming scholarship apps",
        "Planning internships",
        "Reviewing class materials",
        "Making a collaborative study notebook"
    ]

    # Create images directory if it doesn't exist
    os.makedirs("images", exist_ok=True)

    # Initialize Supabase client
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_KEY")
    supabase: Client = create_client(supabase_url, supabase_key)

    client = genai.Client(api_key=os.getenv("GEMINI_API"))

    total = len(activities_list)
    for idx, activity in enumerate(activities_list, 1):
        print(f"\n[{idx}/{total}] Processing: {activity}")
        prompt = generate_prompt(activity)

        response = client.models.generate_content(
            model="gemini-2.5-flash-image",
            contents=[prompt],
        )

        for part in response.parts:
            if part.text is not None:
                print(part.text)
            elif part.inline_data is not None:
                image = part.as_image()
                # sanitize the file name
                safe_filename = activity.replace(" ", "_").replace("/", "_").replace("\\", "_").replace(":", "_")
                filepath = f"images/{safe_filename}.png"
                image.save(filepath)
                print(f"✓ Saved locally: {filepath}")
                
                # Upload to Supabase Storage
                try:
                    with open(filepath, "rb") as f:
                        supabase.storage.from_("activity-images").upload(
                            path=f"{safe_filename}.png",
                            file=f,
                            file_options={"content-type": "image/png"}
                        )
                    print(f"✓ Uploaded to Supabase: {safe_filename}.png")
                except Exception as e:
                    print(f"✗ Upload failed: {e}")
    
    return
    

if __name__ == "__main__":
    main()